In [ ]:
# 1 
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
z = np.zeros((2, 3))
print(z)

o = np.ones((2, 2))
print(o)
r = np.arange(0, 10, 2)
print(r)
l = np.linspace(0, 1, 5)
print(l)

rand = np.random.rand(2, 2)
print(rand)

In [ ]:
# 2 Array Properties and Inspection
#shape
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
#dimension
print(arr.ndim)

#size
print(arr.size)

#type
print(arr.dtype)

#mem usage
print(arr.itemsize)


In [ ]:
# 3 Index & Slicing
import numpy as np
# basic indexing
arr = np.array([10, 20, 30])
print(arr[2])

#slicing
print(arr[0:1])

# 2D indexing
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat[1, 2])

#boolean indexing
print(mat[mat > 2])

# fancy indexing
brr = np.array([10, 20, 30, 40])
print(brr[[0, 3]])


In [ ]:
# 4 Reshaping and Structural Changes
# reshape
import numpy as np
arr = np.arange(6)
print(arr.reshape(2, 3))

# flatten
mat = np.array([[1, 2], [3, 4]])
print(mat.flatten())

# transpose
print(mat.T)

# concatenate
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))

# stack
print(np.stack((a, b)))

In [13]:
# 5 Data Type Conversion
# convert to float
import numpy as np
arr = np.array([1, 2, 3])
print(arr.astype(np.float64))

[1. 2. 3.]


In [14]:
# 6 Mathematical Operation
# arithmetic
import numpy as np
arr = np.array([1, 2, 3])
print(arr + 5)
print(arr * 5)

# element-wise between 1D arrays
a = np.array([10, 20, 30, 40, 50])
b = np.array([60, 70, 80, 90, 100])
print(a+b)

# universal functions
print(np.sqrt(arr))
print(np.exp(arr))

[6 7 8]
[ 5 10 15]
[ 70  90 110 130 150]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


In [ ]:
# 7 Statistical Operation
# Mean
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))

# median
print(np.median(arr))

# standard deviation
print(np.std(arr))

# variance
print(np.var(arr))

2.5
2.5
1.118033988749895


In [ ]:
# 8 Aggregation along axes
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.mean(arr, axis=0))

[5 7 9]
[ 6 15]
[2.5 3.5 4.5]


In [19]:
# 9 Broadcasting
# vector + matrix
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([10, 20, 30])
print(arr + v)

print(arr + 5)

[[11 22 33]
 [14 25 36]]
[[ 6  7  8]
 [ 9 10 11]]


In [22]:
# 10 Linear Algebra Operation
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.matmul(A, B))
print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.inv(A))
print(np.linalg.inv(B))
print(np.linalg.eig(A))
print(np.linalg.eig(B))

[[19 22]
 [43 50]]
-2.0000000000000004
-2.000000000000005
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-4.   3. ]
 [ 3.5 -2.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
EigResult(eigenvalues=array([-0.15206735, 13.15206735]), eigenvectors=array([[-0.75868086, -0.59276441],
       [ 0.65146248, -0.80537591]]))
